# Generated by Django 5.0.6 on 2024-06-06 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(blank=True, max_length=256, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=256, null=True)),
                ('author_rus', models.CharField(blank=True, max_length=256, null=True)),
                ('author_eng', models.CharField(blank=True, max_length=256, null=True)),
                ('keyword_rus', models.CharField(blank=True, max_length=256, null=True)),
                ('keyword_eng', models.CharField(blank=True, max_length=256, null=True)),
                ('publish_year', models.IntegerField()),
                ('link', models.URLField(max_length=2083)),
                ('usage_context', models.CharField(blank=True, max_length=1024, null=True)),
                ('maths', models.CharField(blank=True, max_length=256, null=True)),
                ('article_idfr', models.CharField(max_length=256)),
                ('problems_solution', models.CharField(blank=True, max_length=1024, null=True)),
                ('term', models.CharField(max_length=256)),
                ('term_desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('interest', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('user_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_articles', to=settings.AUTH_USER_MODEL)),
                ('user_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
